[tool.poetry]
name = "web-ui"
version = "0.1.0"
description = "Engelina web ui"
authors = ["rudast <ruslan5haertdinov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
